// GENERATED by media-src/scripts/fetch-echarts-themes.mjs — do not edit by hand.
//
// A curated set of Apache ECharts' built-in gallery themes (theme/<name>.js), captured as plain
// data so the webview can `echarts.registerTheme` them for the `vmarkd.theme.echarts` setting
// (task 90). Apache-2.0 — see media-src/vendor/echarts/{LICENSE,NOTICE}.
// Source: echarts@6.1.0/theme/*.js.

export const ECHARTS_GALLERY: Record<string, Record<string, unknown>> = {
  vintage: {
    color: [
      '#d87c7c',
      '#919e8b',
      '#d7ab82',
      '#6e7074',
      '#61a0a8',
      '#efa18d',
      '#787464',
      '#cc7e63',
      '#724e58',
      '#4b565b',
    ],
    backgroundColor: '#fef8ef',
    graph: {
      color: [
        '#d87c7c',
        '#919e8b',
        '#d7ab82',
        '#6e7074',
        '#61a0a8',
        '#efa18d',
        '#787464',
        '#cc7e63',
        '#724e58',
        '#4b565b',
      ],
    },
  },
  macarons: {
    color: [
      '#2ec7c9',
      '#b6a2de',
      '#5ab1ef',
      '#ffb980',
      '#d87a80',
      '#8d98b3',
      '#e5cf0d',
      '#97b552',
      '#95706d',
      '#dc69aa',
      '#07a2a4',
      '#9a7fd1',
      '#588dd5',
      '#f5994e',
      '#c05050',
      '#59678c',
      '#c9ab00',
      '#7eb00a',
      '#6f5553',
      '#c14089',
    ],
    title: {
      textStyle: {
        fontWeight: 'normal',
        color: '#008acd',
      },
    },
    visualMap: {
      itemWidth: 15,
      color: ['#5ab1ef', '#e0ffff'],
    },
    toolbox: {
      iconStyle: {
        borderColor: '#2ec7c9',
      },
    },
    tooltip: {
      borderWidth: 0,
      backgroundColor: 'rgba(50,50,50,0.5)',
      textStyle: {
        color: '#FFF',
      },
      axisPointer: {
        type: 'line',
        lineStyle: {
          color: '#008acd',
        },
        crossStyle: {
          color: '#008acd',
        },
        shadowStyle: {
          color: 'rgba(200,200,200,0.2)',
        },
      },
    },
    dataZoom: {
      dataBackgroundColor: '#efefff',
      fillerColor: 'rgba(182,162,222,0.2)',
      handleColor: '#008acd',
    },
    grid: {
      borderColor: '#eee',
    },
    categoryAxis: {
      axisLine: {
        lineStyle: {
          color: '#008acd',
        },
      },
      splitLine: {
        lineStyle: {
          color: ['#eee'],
        },
      },
    },
    valueAxis: {
      axisLine: {
        lineStyle: {
          color: '#008acd',
        },
      },
      splitArea: {
        show: true,
        areaStyle: {
          color: ['rgba(250,250,250,0.1)', 'rgba(200,200,200,0.1)'],
        },
      },
      splitLine: {
        lineStyle: {
          color: ['#eee'],
        },
      },
    },
    timeline: {
      lineStyle: {
        color: '#008acd',
      },
      controlStyle: {
        color: '#008acd',
        borderColor: '#008acd',
      },
      symbol: 'emptyCircle',
      symbolSize: 3,
    },
    line: {
      smooth: true,
      symbol: 'emptyCircle',
      symbolSize: 3,
    },
    candlestick: {
      itemStyle: {
        color: '#d87a80',
        color0: '#2ec7c9',
      },
      lineStyle: {
        width: 1,
        color: '#d87a80',
        color0: '#2ec7c9',
      },
      areaStyle: {
        color: '#2ec7c9',
        color0: '#b6a2de',
      },
    },
    scatter: {
      symbol: 'circle',
      symbolSize: 4,
    },
    map: {
      itemStyle: {
        color: '#ddd',
      },
      areaStyle: {
        color: '#fe994e',
      },
      label: {
        color: '#d87a80',
      },
    },
    graph: {
      itemStyle: {
        color: '#d87a80',
      },
      linkStyle: {
        color: '#2ec7c9',
      },
    },
    gauge: {
      axisLine: {
        lineStyle: {
          color: [
            [0.2, '#2ec7c9'],
            [0.8, '#5ab1ef'],
            [1, '#d87a80'],
          ],
          width: 10,
        },
      },
      axisTick: {
        splitNumber: 10,
        length: 15,
        lineStyle: {
          color: 'auto',
        },
      },
      splitLine: {
        length: 22,
        lineStyle: {
          color: 'auto',
        },
      },
      pointer: {
        width: 5,
      },
    },
  },
  infographic: {
    color: [
      '#C1232B',
      '#27727B',
      '#FCCE10',
      '#E87C25',
      '#B5C334',
      '#FE8463',
      '#9BCA63',
      '#FAD860',
      '#F3A43B',
      '#60C0DD',
      '#D7504B',
      '#C6E579',
      '#F4E001',
      '#F0805A',
      '#26C0C0',
    ],
    title: {
      textStyle: {
        fontWeight: 'normal',
        color: '#27727B',
      },
    },
    visualMap: {
      color: ['#C1232B', '#FCCE10'],
    },
    toolbox: {
      iconStyle: {
        borderColor: '#C1232B',
      },
    },
    tooltip: {
      backgroundColor: 'rgba(50,50,50,0.5)',
      axisPointer: {
        type: 'line',
        lineStyle: {
          color: '#27727B',
          type: 'dashed',
        },
        crossStyle: {
          color: '#27727B',
        },
        shadowStyle: {
          color: 'rgba(200,200,200,0.3)',
        },
      },
    },
    dataZoom: {
      dataBackgroundColor: 'rgba(181,195,52,0.3)',
      fillerColor: 'rgba(181,195,52,0.2)',
      handleColor: '#27727B',
    },
    categoryAxis: {
      axisLine: {
        lineStyle: {
          color: '#27727B',
        },
      },
      splitLine: {
        show: false,
      },
    },
    valueAxis: {
      axisLine: {
        show: false,
      },
      splitArea: {
        show: false,
      },
      splitLine: {
        lineStyle: {
          color: ['#ccc'],
          type: 'dashed',
        },
      },
    },
    timeline: {
      itemStyle: {
        color: '#27727B',
      },
      lineStyle: {
        color: '#27727B',
      },
      controlStyle: {
        color: '#27727B',
        borderColor: '#27727B',
      },
      symbol: 'emptyCircle',
      symbolSize: 3,
    },
    line: {
      itemStyle: {
        borderWidth: 2,
        borderColor: '#fff',
        lineStyle: {
          width: 3,
        },
      },
      emphasis: {
        itemStyle: {
          borderWidth: 0,
        },
      },
      symbol: 'circle',
      symbolSize: 3.5,
    },
    candlestick: {
      itemStyle: {
        color: '#c1232b',
        color0: '#b5c334',
      },
      lineStyle: {
        width: 1,
        color: '#c1232b',
        color0: '#b5c334',
      },
      areaStyle: {
        color: '#c1232b',
        color0: '#27727b',
      },
    },
    graph: {
      itemStyle: {
        color: '#c1232b',
      },
      linkStyle: {
        color: '#b5c334',
      },
    },
    map: {
      itemStyle: {
        color: '#f2385a',
        areaColor: '#ddd',
        borderColor: '#eee',
      },
      areaStyle: {
        color: '#fe994e',
      },
      label: {
        color: '#c1232b',
      },
    },
    gauge: {
      axisLine: {
        lineStyle: {
          color: [
            [0.2, '#B5C334'],
            [0.8, '#27727B'],
            [1, '#C1232B'],
          ],
        },
      },
      axisTick: {
        splitNumber: 2,
        length: 5,
        lineStyle: {
          color: '#fff',
        },
      },
      axisLabel: {
        color: '#fff',
      },
      splitLine: {
        length: '5%',
        lineStyle: {
          color: '#fff',
        },
      },
      title: {
        offsetCenter: [0, -20],
      },
    },
  },
  roma: {
    color: [
      '#E01F54',
      '#001852',
      '#f5e8c8',
      '#b8d2c7',
      '#c6b38e',
      '#a4d8c2',
      '#f3d999',
      '#d3758f',
      '#dcc392',
      '#2e4783',
      '#82b6e9',
      '#ff6347',
      '#a092f1',
      '#0a915d',
      '#eaf889',
      '#6699FF',
      '#ff6666',
      '#3cb371',
      '#d5b158',
      '#38b6b6',
    ],
    visualMap: {
      color: ['#e01f54', '#e7dbc3'],
      textStyle: {
        color: '#333',
      },
    },
    candlestick: {
      itemStyle: {
        color: '#e01f54',
        color0: '#001852',
      },
      lineStyle: {
        width: 1,
        color: '#f5e8c8',
        color0: '#b8d2c7',
      },
      areaStyle: {
        color: '#a4d8c2',
        color0: '#f3d999',
      },
    },
    graph: {
      itemStyle: {
        color: '#a4d8c2',
      },
      linkStyle: {
        color: '#f3d999',
      },
    },
    gauge: {
      axisLine: {
        lineStyle: {
          color: [
            [0.2, '#E01F54'],
            [0.8, '#b8d2c7'],
            [1, '#001852'],
          ],
          width: 8,
        },
      },
    },
  },
  shine: {
    color: [
      '#c12e34',
      '#e6b600',
      '#0098d9',
      '#2b821d',
      '#005eaa',
      '#339ca8',
      '#cda819',
      '#32a487',
    ],
    title: {
      textStyle: {
        fontWeight: 'normal',
      },
    },
    visualMap: {
      color: ['#1790cf', '#a2d4e6'],
    },
    toolbox: {
      iconStyle: {
        borderColor: '#06467c',
      },
    },
    tooltip: {
      backgroundColor: 'rgba(0,0,0,0.6)',
    },
    dataZoom: {
      dataBackgroundColor: '#dedede',
      fillerColor: 'rgba(154,217,247,0.2)',
      handleColor: '#005eaa',
    },
    timeline: {
      lineStyle: {
        color: '#005eaa',
      },
      controlStyle: {
        color: '#005eaa',
        borderColor: '#005eaa',
      },
    },
    candlestick: {
      itemStyle: {
        color: '#c12e34',
        color0: '#2b821d',
      },
      lineStyle: {
        width: 1,
        color: '#c12e34',
        color0: '#2b821d',
      },
      areaStyle: {
        color: '#e6b600',
        color0: '#005eaa',
      },
    },
    graph: {
      itemStyle: {
        color: '#e6b600',
      },
      linkStyle: {
        color: '#005eaa',
      },
    },
    map: {
      itemStyle: {
        color: '#f2385a',
        borderColor: '#eee',
        areaColor: '#ddd',
      },
      areaStyle: {
        color: '#ddd',
      },
      label: {
        color: '#c12e34',
      },
    },
    gauge: {
      axisLine: {
        show: true,
        lineStyle: {
          color: [
            [0.2, '#2b821d'],
            [0.8, '#005eaa'],
            [1, '#c12e34'],
          ],
          width: 5,
        },
      },
      axisTick: {
        splitNumber: 10,
        length: 8,
        lineStyle: {
          color: 'auto',
        },
      },
      axisLabel: {
        color: 'auto',
      },
      splitLine: {
        length: 12,
        lineStyle: {
          color: 'auto',
        },
      },
      pointer: {
        length: '90%',
        width: 3,
        color: 'auto',
      },
      title: {
        color: '#333',
      },
      detail: {
        color: 'auto',
      },
    },
  },
  'tech-blue': {
    color: [
      '#4d4d4d',
      '#3a5897',
      '#007bb6',
      '#7094db',
      '#0080ff',
      '#b3b3ff',
      '#00bdec',
      '#33ccff',
      '#ccddff',
      '#eeeeee',
    ],
    title: {
      textStyle: {
        fontWeight: 'normal',
        color: '#00aecd',
      },
    },
    visualMap: {
      color: ['#00aecd', '#a2d4e6'],
    },
    toolbox: {
      color: ['#00aecd', '#00aecd', '#00aecd', '#00aecd'],
    },
    tooltip: {
      backgroundColor: 'rgba(0,0,0,0.5)',
      axisPointer: {
        type: 'line',
        lineStyle: {
          color: '#00aecd',
          type: 'dashed',
        },
        crossStyle: {
          color: '#00aecd',
        },
        shadowStyle: {
          color: 'rgba(200,200,200,0.3)',
        },
      },
    },
    dataZoom: {
      dataBackgroundColor: '#eee',
      fillerColor: 'rgba(144,197,237,0.2)',
      handleColor: '#00aecd',
    },
    timeline: {
      lineStyle: {
        color: '#00aecd',
      },
      controlStyle: {
        color: '#00aecd',
      },
      emphasis: {
        controlStyle: {
          color: '#00aecd',
        },
      },
    },
    candlestick: {
      itemStyle: {
        color: '#ddd',
        color0: '#eee',
      },
      lineStyle: {
        width: 1,
        color: '#33ccff',
        color0: '#1bb4cf',
      },
      areaStyle: {
        color: '#7094db',
        color0: '#33ccff',
      },
    },
    chord: {
      padding: 4,
      itemStyle: {
        color: '#7094db',
        borderWidth: 1,
        borderColor: 'rgba(128, 128, 128, 0.5)',
      },
      lineStyle: {
        color: 'rgba(128, 128, 128, 0.5)',
      },
      areaStyle: {
        color: '#33ccff',
      },
    },
    graph: {
      itemStyle: {
        color: '#7094db',
      },
      linkStyle: {
        color: '#33ccff',
      },
    },
    map: {
      itemStyle: {
        color: '#7094db',
      },
      areaStyle: {
        color: '#33ccff',
      },
      label: {
        color: '#ddd',
      },
    },
    gauge: {
      axisLine: {
        lineStyle: {
          color: [
            [0.2, '#dddddd'],
            [0.8, '#00aecd'],
            [1, '#33ccff'],
          ],
          width: 8,
        },
      },
    },
  },
}

/** The gallery theme ids (the `theme.echarts` values beyond auto / light / dark). */
export const ECHARTS_GALLERY_NAMES: readonly string[] =
  Object.keys(ECHARTS_GALLERY)
